name: Build and publish BedWars master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set the Build number
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo ::set-env name=BUILD_NUMBER::$(($NUM+865))
      - run: echo "Build number for this commit is $BUILD_NUMBER"
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew
        env:
          NEXUS_URL_RELEASE: ${{ secrets.NEXUS_URL_RELEASE }}
          NEXUS_URL_SNAPSHOT: ${{ secrets.NEXUS_URL_SNAPSHOT }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          JAVADOC_HOST: ${{ secrets.JAVADOC_HOST }}
          JAVADOC_SECRET: ${{ secrets.JAVADOC_SECRET }}
          JAVADOC_USER: ${{ secrets.JAVADOC_USER }}
          OPTIMIZE_FOR_CI_CD: "1"
        - name: Upload the final artifact
          uses: actions/upload-artifact@v2
          with:
            path: plugin/build/libs/BedWars*[!s].jar
